__include__: [
  '../dataset/open.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


tuning: ./output/open/rtdetrv2_r50vd_dsp_1x_coco/best.pth

output_dir: ./output/challenge/rtdetrv2_r50vd_dsp_1x_coco


RTDETRTransformerv2:
  cross_attn_method: discrete


epoches: 12

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 10
  collate_fn:
    stop_epoch: 10
